### ISSUE TITLE
"RuntimeError: CUDA error: invalid device function" during training

### ISSUE THREAD

**Issue by liangzhiyuanCV** [qjy981010/CMaskTrack-RCNN#1]
Some problems occur when I launch the training script. The error information is as follow,
Traceback (most recent call last):                                                                                                                                                             
  File "train.py", line 103, in <module>                                                                                                                                                       
    main()                                                                                                                                                                                     
  File "train.py", line 99, in main                                                                                                                                                            
    logger=logger)                                                                                                                                                                             
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/apis/train.py", line 60, in train_detector                                                                                                
    _non_dist_train(model, dataset, cfg, validate=validate, logger = logger)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/apis/train.py", line 124, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/liangzhiyuan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liangzhiyuan/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/liangzhiyuan/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/liangzhiyuan/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/liangzhiyuan/.local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/liangzhiyuan/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/liangzhiyuan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/models/detectors/base.py", line 85, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/models/detectors/two_stage.py", line 117, in forward_train
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/models/anchor_heads/anchor_head.py", line 232, in get_bboxes
    scale_factor, cfg, rescale)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/models/anchor_heads/rpn_head.py", line 80, in get_bboxes_single
    proposals, _ = nms(proposals, cfg.nms_thr)
  File "/data/liangzhiyuan/projects/CMaskTrack/mmdet/ops/nms/nms_wrapper.py", line 35, in nms
    return dets[inds, :], inds
RuntimeError: CUDA error: invalid device function
----------------------------------------
The pytorch version is 1.3.1 with cuda10.1, and the torchvision is 0.2.2.

**Comment by qjy981010** [comment]
It may be caused by CUDA version mismatch. Please refer to [this comment](https://github.com/open-mmlab/mmdetection/issues/1961#issuecomment-576282929) in the mmdetection repo.

To specify the cuda version for compiling `ops`, you can uncomment [these three lines](https://github.com/qjy981010/CMaskTrack-RCNN/blob/32746b9f30a86fe72bbfb6c764180afc501f66ee/compile.sh#L4) and replace the `cuda-10.0` with your cuda version.

**Comment by liangzhiyuanCV** [comment]
Thanks for your help. I have figured out this problem by changing the cuda version from 10.1 to 10.0
